app :
  frontend:
    reset-password-url: https://spa-retail-dev.up.railway.app/reset-password

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}

auth:
  users:
    - username: user
      password: ${LOCAL_PASSWORD:user}
      roles: USER
    - username: admin
      roles: ADMIN
      password: ${LOCAL_PASSWORD:admin}
  jwt:
    public-key: ${JWT_PUBLIC_KEY}
    private-key: ${JWT_PRIVATE_KEY}