package com.academy.orders.infrastructure.postaddress.repository;

import com.academy.orders.infrastructure.postaddress.entity.PostAddressV2Entity;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Repository
public interface PostAddressJpaAdapter extends CrudRepository<PostAddressV2Entity, UUID> {
  /**
   * Retrieves a post address V2 entity by its title and associated account ID. This method is used to ensure that each account has unique
   * permanent post address titles.
   *
   * @param title the title of the post address (e.g., "permanent: Home").
   * @param accountId the ID of the account that owns the post address.
   * @return {@link Optional} containing the {@link PostAddressV2Entity} if found, or an empty {@link Optional} if not.
   * @author Oleksandra Bulhakova
   */
  Optional<PostAddressV2Entity> findByTitleAndAccount_Id(String title, Long accountId);

  /**
   * Retrieves all post address entities for a given account that are marked as permanent. A permanent post address is identified by the
   * "permanent: " prefix in its title.
   *
   * @param accountId the ID of the account whose permanent post addresses are to be retrieved
   * @return a list of {@link PostAddressV2Entity} entries with titles starting with "permanent: " associated with the given account
   * @author Oleksandra Bulhakova
   */
  @Query("""
      SELECT p FROM PostAddressV2Entity p WHERE p.account.id = :accountId AND p.title like 'permanent: %'
      """)
  List<PostAddressV2Entity> findPermanentPostAddressesByAccountId(@Param("accountId") Long accountId);

  /**
   * Checks whether the post address with the specified ID has a title starting with the given prefix.
   *
   * @param addressId the UUID of the post address to check
   * @param prefix    the prefix that should be present at the beginning of the title
   * @return {@code true} if a post address with the given ID exists and its title starts with the specified prefix,
   *         {@code false} otherwise
   * @author Oleksandra Bulhakova
   */
  boolean existsByIdAndTitleStartingWith(UUID addressId, String prefix);

  /**
   * Updates the title of the post address with the specified ID to mark it as temporary.
   * The new title is generated by concatenating the "temp: " prefix with a randomly generated UUID.
   * This operation is executed as an update query and does not load the entity into the persistence context.
   *
   * @param addressId the UUID of the post address to update
   * @author Oleksandra Bulhakova
   */
  @Modifying
  @Query("""
          UPDATE PostAddressV2Entity p SET p.title = CONCAT ('temp: ', FUNCTION('gen_random_uuid')) WHERE p.id = :addressId AND p.title like 'permanent: %'
          """)
  void setAddressTitleToTemporary(@Param("addressId") UUID addressId);
}
